### ISSUE TITLE
instead of sorting use max()

### ISSUE THREAD

**Issue by umuterturk** [gokhankar/practicepython#2]
https://github.com/gokhankar/practicepython/blob/8bbcae8d5ee50ef98babe9dd485cc639226d7ddf/28_max_of_three.py#L10

**Comment by gokhankar** [comment]
Thanks Umut, it is may be the fastest way but instructions of the exercise restricts to use max() function.

---Implement a function that takes as input three variables, and returns the largest of the
---three. Do this without using the Python max() function!
